### ISSUE TITLE
(Not an issue) Thanks for making this repo! It's interesting!

### ISSUE THREAD

**Issue by loneicewolf** [MBHudson/irShell#1]
Hello! 
Sorry to make (not a) issue (but a thank you word).
Have a great week!

//Will.

**Comment by loneicewolf** [comment]
this ''issue'' can be closed whenever, it's just to show my appreciation. I always make a issue to 'say thanks' if I find a very good(in some way) repo. I.e I thank users who make (to me) good repo's that I find useful, but also repos like this one, which I find interesting. And I know there are a lot of "shell" repos, but this one caught my eye. :)

Regards!

**Comment by MBHudson** [comment]
Thank you very much for the nice words and for taking the time to express them. It's appreciated so much, this made my whole day.

**Comment by loneicewolf** [comment]
Oh! very quick reply! No problems, and thanks. `:-)`
